title: alxfed.github.io
description: alxfed, mathematics, statistics, environment, physics, social statistics
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
